server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/admin_system?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  redis:
    host: 192.168.81.130
    port: 6379
    timeout: 3000


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml

jwt-utils:
  jwt:
    header: Authorization
#   jwt过期时间，单位：秒
    expire: 6048
    secret: fdhgiuasghdfiaghiaohsgfoaisdgfoaisdgfioas


sys-default-setting:
# ===================== portainer 连接设置 ==========================
  portainer-access-token: ptr_UftpSP8+k8AXRTkHOaQ4txD7+wDMSGS53SavxJxXBW4=
  portainer-url: http://localhost:9000/api

#  ====================== 工单系统连接设置 ====================
  wos-access-token: 123www
  wos-url: http://localhost:8080/backendApi
# ======================== 计时器设置 ====================

#   自动校对信息间隔（数据库查询间隔 单位：s） 1000 * {n}
  timer-check: 60
# 用户过期时间 单位：天 (1000 * 60 * 60 * 24 * 30 * {n})
  timer-single-gpu-expire: 6
  timer-group-gpu-expire: 6
# 容器清理时间
  timer-single-gpu-clear: 6
  timer-group-gpu-clear: 6
